# Generated by Django 4.0.1 on 2022-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='percentaje',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
