# Generated by Django 4.0.1 on 2022-01-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectify', '0002_alter_report_percentaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='percentaje',
            new_name='percentage',
        ),
    ]
