# Generated by Django 4.0.1 on 2022-01-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectify', '0003_rename_percentaje_report_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
    ]
