# Generated by Django 4.0.1 on 2022-01-17 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectify', '0004_alter_report_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
